### ISSUE TITLE
Kan niet pushen 

### ISSUE THREAD

**Issue by sandercop** [baha90210/eventplanner_front#2]
fatal: unable to access 'https://sander.coppoolse%40gmail.com@github.com/baha90210/eventplanner_front.git/': The requested URL returned error: 403

Ik probeer morgen nog wel eens op een andere manier.

**Comment by sandercop** [comment]
Eigen fork gemaakt die ik wel kan pushen.

**Comment by bxck75** [comment]
installeer in vredes naam  sourcetree
die doet namelijk het checken en mergen voor je en je hebt mee overzicht
van wat je doet
op git

werkt ook goed met netbeans

groeten

Boudewijn

2015-02-04 23:02 GMT+01:00 sandercop notifications@github.com:

**Comment by bxck75** [comment]
Die fork gaat niet werken want daar komen onze veranderingen niet meer in

**Comment by bxck75** [comment]
wij blijven namelijk in de master tree werken

**Comment by sandercoppoolse** [comment]
Ik denk dat ik weet waar het aan licht.
Bart heeft de verkeerde github account toegevoegd merk ik, mijn oude ' werk ' account.
Zal even wat rommelen :)

**Comment by sandercoppoolse** [comment]
Dat werkt nu, moet even specifiek accounts switchen als ik hier wil pushen. 
Zal Bart wel even vragen dat te veranderen en die 'werk' account even non actief zetten.

g'avond :)

**Comment by bxck75** [comment]
ben blij dat ik sourcetree heb....duidelijk overzicht van commits en push/pulls

als je namelijk begint te werken.....zonder eerst een pull te doen van de laatste versie....krijg je 9 van de 10 keer problemen met commit
en push

dus workflow is 

eerst pull voor ook maar een letter code te kloppen

**Comment by bxck75** [comment]
later.......

**Comment by sandercop** [comment]
Klopt maar als ik geen member ben kan ik pushen wat ik wil maar dan lukt het toch echt niet:)

**Comment by bxck75** [comment]
hahahahmeestal zo met die push clubjes
